### ISSUE TITLE
No coverage object in the browser

### ISSUE THREAD

**Issue by ghost** [r3b/grunt-protractor-coverage#10]
I'm getting this message in the output:
"No coverage object in the browser"

lkrnac appeared to run into the same message in issue #1. Did it get resolved? 
https://github.com/r3b/grunt-protractor-coverage/issues/1 

Thanks.

**Comment by F1LT3R** [comment]
I'm getting `No coverage object in the browser.` too.

**Comment by F1LT3R** [comment]
@bizob2828  did you ever post that gist? I think I am running in to the same issue as you.

**Comment by F1LT3R** [comment]
@r3b how do you verify the instrumented javascript folder is being served up to protractor?

**Comment by DimoDimov** [comment]
I had the same issue. I fix my problem by setting relative path with my server. Because even if you instrument the server and move it with your static folder it will still look for the absolute paths instead for the relative.

Example:

if your node code looks like this:

    app.use(express.static('./public'));
it should be changed to look like this:

    app.use(express.static(path.resolve(__dirname, '../public')));
this way when your instrumented code is moved to a new 'instrumented folder' it will look for you instrumented 'public' directory relatively inside the 'instrument'.

What happens now is that you have you js files instrumented (C) and (D) which is totally what you need.

The problem begins when you run the server code (D) where absolute path points to (A) instead of (C). So you instrumented server runs the non instrumented front end. You fix this by setting the server to look relatively, not by absolute path.

/public (A) -> clean front end code
/server (B) -> clean back end code
/instrumented
   /public -> (C) instrumented front end code
   /server -> (D) instrumented back end code

**Comment by ARenfroe** [comment]
@r3b I am running into the same problem.
node v4.3.2
protractor v3.3.0

I am serving the instrumented code up to protractor (I believe).

**gruntfile**

    app name: {
        // configurable paths
        client: require('./bower.json').appPath || 'client',
        server: './server.js',
        dist: 'dist',
        coverageE2E: './coverage/e2e',
        coverageServer: 'instrumented/server.js',
        mocha: 'services/test/'
    },
        express: {
            options: {
                 },
            dev: {
                script: '<%= appname.server %>',
                debug: true
              }
            },
            prod: {
              // options: {
              //   script: '<%= appname.dist %>/<%= appname.server %>'
              // }
            },
            coverage: {
                options: {
                    port: 9000,
                    //script: '<%= appname.coverageServer %>'
                    script: 'instrumented/server.js'
                }
            }
        },
        env: {
            test: {
            },
            development: {
                NODE_ENV: 'development'
            },
            stage: {
                NODE_ENV: 'stage'
            },
            prod: {
                NODE_ENV: 'production'
            },
            coverage: {
                NODE_ENV: 'test',
                PROTRACTOR_SITE: 'http://url.url.com:9000',
                PROTRACTOR_ENV: 'stage',
                CAN_SEED_DB: 'true',
                XIP_SUBDOMAIN: 'local'
            },
            all: localConfig
        },
    instrument: {
        files: [
            'app/dist/**/*.js',
            'config/**/*.js',
            'scripts/**/*.js',
            '*.js'
        ],
        options: {
            lazy: true,
            basePath: 'instrumented'
        }
    },
    protractor_coverage: {
        options: {
            keepAlive: true,
            noColor: false,
            //coverageDir: '<%= appname.coverageE2E %>',
            coverageDir: 'instrumented',
            args: {
                baseUrl: 'http://url.url.com:9000/#/login/'
            }
        },
        default: {
            //configFile: 'test.old/protractor/conf.js'
            configFile: "./node_modules/path/protractor.conf.js"
        }
    },
    makeReport: {
        src: 'coverage/*.json',
        options: {
            type: 'lcov',
            dir: 'coverage/',
            print: 'detail'
        }
    },
    copy: {
       cover: {
          files: [{
             expand: true,
             src: [ '**/*.*', '!*.js', '!./node_modules/*'],
                dest: './instrumented'
          }]
       }
    },


**output**

```
Running "protractor_coverage:default" (protractor_coverage) task
>> SauceLab is not enabled.
**Collector started on port 3001**
>> SauceLab is not enabled.
[16:53:51] I/local - Starting selenium standalone server...
[16:53:51] I/launcher - Running 1 instances of WebDriver
[16:53:52] I/local - Selenium standalone server started at http://ip:port/wd/hub


  Login

    ✓ should login (4509ms)

No coverage object in the browser.

  Login
    ✓ should login
No coverage object in the browser.


  2 passing (7s)

[16:54:01] I/local - Shutting down selenium standalone server.
[16:54:01] I/launcher - 0 instance(s) of WebDriver still running
[16:54:01] I/launcher - chrome #01 passed
Shutdown requested

Running "makeReport" task
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|

Done, without errors.


Execution Time (2016-06-03 23:48:46 UTC)
clean:coverage                  17.6s  ▇▇▇ 6%
instrument                       7.4s  ▇ 2%
copy:cover                    2m 9.2s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 41%
express:coverage                 6.1s  ▇ 2%
protractor_coverage:default  2m 34.5s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 49%
Total 5m 15s
```


The only thing I see is **Collector started on port 3001** but I'm not sure where to change this.

**Comment by ARenfroe** [comment]
@r3b I just started getting this error from the runs on codeship.  

**output from codeship**
```
  12) should 
No coverage object in the browser.
  13) should check 
No coverage object in the browser.
  - should 
  - should 
  - should 
  14) should enter address
No coverage object in the browser.
  - should
  - should invoke garbage collection
  15) should logout
No coverage object in the browser.


  0 passing (2m)
  5 pending
  15 failing

  1) Staff Ordering should login:
     Error: done() invoked with non-Error: Error while running testForAngular: asynchronous script timeout: result was not received in 110 seconds
(Session info: chrome=52.0.2743.82)
(Driver info: chromedriver=2.21.371461 (<removed for github comment>)
,platform=Linux 4.2.0-42-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 110.07 seconds
Build info: version: '2.52.0', revision: '4c2593c', time: '2016-02-11 19:06:42'
System info: host: '<removed for github comment>', ip: '<removed for github comment>', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-42-generic', java.version: '1.7.0_101'
Session ID: <removed for github comment>
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{platform=LINUX, acceptSslCerts=true, javascriptEnabled=true, browserName=chrome, chrome={userDataDir=/tmp/.com.google.Chrome.wTriGJ, chromedriverVersion=2.21.371461 (<removed for github comment>)}, rotatable=false, locationContextEnabled=true, mobileEmulationEnabled=false, version=52.0.2743.82, takesHeapSnapshot=true, cssSelectorsEnabled=true, databaseEnabled=false, handlesAlerts=true, browserConnectionEnabled=false, webStorageEnabled=true, nativeEvents=true, hasTouchScreen=false, applicationCacheEnabled=false, takesScreenshot=true}]
at Promise.invokeCallback_ (node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:1329:14)
at TaskQueue.execute_ (node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2790:14)
at TaskQueue.executeNext_ (node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2773:21)
at node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:2652:27
at node_modules/protractor/node_modules/selenium-webdriver/lib/promise.js:639:7

```

The runs on my local machine are fine.  I wrapped my unit tests, e2e tests, make reports, and sending to coveralls into one grunt task.  As of recently I also started to get 100% line coverage reporting from my protractor tests?  

**output from local machine**
```
  15 passing (2m)
  5 pending
```
