### ISSUE TITLE
Does not work with spec patterns not relative to the config location

### ISSUE THREAD

**Issue by DmitryGonchar** [r3b/grunt-protractor-coverage#18]
Even in your repository, your [config file](https://github.com/r3b/grunt-protractor-coverage/blob/master/test/protractorConf.js) is in "test" folder, however paths still include "test/"

```
// Spec patterns are relative to the location of this config.
  specs: [
    'test/protractor/*.spec.js',
    '!**/exclude.spec.js'
  ],
  exclude: ['test/protractor/exclude2.spec.js'],
```

In my project, I tried to change these paths to relative (removed "test/") and protractor-coverage did not work. If absolute paths (like the ones above) are used, the problem is that protractor (grunt-protractor-runner) does not work :(

**Comment by evilaliv3** [comment]
this is stil not solved right or am i wrong?
