### ISSUE TITLE
not able to run gruntfile included in npm package

### ISSUE THREAD

**Issue by sanjeevmajgotra** [r3b/grunt-protractor-coverage#27]
I'm new to nodejs programming so please help me out here. I'm not able to execute the deafult gruntfile included in Window's seven environement. The basic error i'm getting is 
 1) Exception loading: C:\Users\<myusername>\AppData\Local\Temp\1415630349701.6733 Error
  Message:
    Error: Cannot find module 'coverage-collector'
  Stacktrace:
    Error: Cannot find module 'coverage-collector'
   at require (module.js:380:17)
   at Object.<anonymous> (C:\Users\majgotra\AppData\Local\Temp\1415630349701.6733:3:1)
. But I've checked inside the local node_modules folder and the coverage-collector folder is there. I've even tried deleting and then reinstalling it but nothing helped. PFB the full stack trace
Running "jshint:all" (jshint) task
>> 3 files lint free.

Running "clean:tests" (clean) task
Cleaning "instrumented"...OK
Cleaning "coverage"...OK
Cleaning "reports"...OK

Running "copy:instrument" (copy) task
Created 12 directories, copied 7 files

Running "instrument" task
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK
OK

Running "connect:server" (connect) task
Started connect web server on http://0.0.0.0:3000

Running "protractor_coverage:local" (protractor_coverage) task
Collector started on port 3001
Using the selenium server at http://localhost:4444/wd/hub
Exception loading: C:\Users\majgotra\AppData\Local\Temp\1415630482346.2195
  Error - fail

Failures:

  1) Exception loading: C:\Users\majgotra\AppData\Local\Temp\1415630482346.2195 Error
   Message:
     Error: Cannot find module 'coverage-collector'
   Stacktrace:
     Error: Cannot find module 'coverage-collector'
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\majgotra\AppData\Local\Temp\1415630482346.2195:3:1)

Finished in 0.007 seconds
1 test, 1 assertion, 1 failure

>>
>> Test failed but keep the grunt process alive.
Shutdown requested

Running "makeReport" task
----------|-----------|-----------|-----------|-----------|
File      |   % Stmts |% Branches |   % Funcs |   % Lines |
----------|-----------|-----------|-----------|-----------|
----------|-----------|-----------|-----------|-----------|
All files |       100 |       100 |       100 |       100 |
----------|-----------|-----------|-----------|-----------|

OK

Running "coveralls:main" (coveralls) task

Can you please help

**Comment by r3b** [comment]
Apologies for the slow response. It looks like Coveralls.io may have been having an issue with ther service. This isn't a credentials error and I am currently able to connect and submit without issue. Have you been able to try again?
