### ISSUE TITLE
How to pass complex params to protractor from command line?

### ISSUE THREAD

**Issue by dmitry-dedukhin** [r3b/grunt-protractor-coverage#3]
In case of manual run I can do something like this:

```
node_modules/protractor/bin/protractor --params.someParam=someVal
```

But I can't figure out how to pass such argument using command line with grunt task:

```
// doesn't work
grunt coverage --params.someParam=someVal
```

In issue https://github.com/r3b/grunt-protractor-coverage/issues/1 you mentioned [dargs-object](https://www.npmjs.org/package/dargs-object) but I can't understand how it can helps me in this case.
I can't specify some params in Gruntfile and I want to pass them from command line when I run grunt.

**Comment by startswithaj** [comment]
@r3b did you ever get this to work?

Could you provide an example if you did?

Cheers
