### ISSUE TITLE
Reports not getting generated properly

### ISSUE THREAD

**Issue by softvar** [r3b/grunt-protractor-coverage#38]
Have asked this question on StackOverflow but didn't get any responses. Here's the link http://stackoverflow.com/questions/18773598/creating-folders-inside-github-com-repo-without-using-git/18791455#18791455

Hope to find the workaround.

Thanks
@softvar

**Comment by r3b** [comment]
The link you provided doesn't appear to be relevant to this project. Feel free to reopen the ticket with a bit more explanation if I am mistaken.

**Comment by softvar** [comment]
Sorry @r3b , seems I copied the wrong url.
Please see the updated one: http://stackoverflow.com/questions/28536755/protractor-coverage-not-generating-report

**Comment by TammyN** [comment]
I'm having the same issue.

**Comment by garimamathur16** [comment]
Hi,
@softvar @TammyN Did you guys find a solution to this issue?
I am facing this issue too. Please let me know, if you managed to come up with any solution.

**Comment by softvar** [comment]
Hey @garimamathur16 Nope, I didn't get the response from anywhere and I didn't struggle much afterwards. It seems there's no active community to look deep into it, please let me know if you'll happen to find a solution somehow.

**Comment by youthcoder1705** [comment]
@softvar @garimamathur16 @TammyN, you might want to change the makeReport config in Gruntfile.js

Point the src to the directory where json file placed not "coverage/**/*.json"

Worked for me.
